/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    'payload-users': PayloadUserAuthOperations;
  };
  collections: {
    'payload-users': PayloadUser;
    'payload-pages': PayloadPage;
    'payload-blog-posts': PayloadBlogPost;
    'payload-media': PayloadMedia;
    'payload-services': PayloadService;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'payload-users': PayloadUsersSelect<false> | PayloadUsersSelect<true>;
    'payload-pages': PayloadPagesSelect<false> | PayloadPagesSelect<true>;
    'payload-blog-posts': PayloadBlogPostsSelect<false> | PayloadBlogPostsSelect<true>;
    'payload-media': PayloadMediaSelect<false> | PayloadMediaSelect<true>;
    'payload-services': PayloadServicesSelect<false> | PayloadServicesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: PayloadUser & {
    collection: 'payload-users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PayloadUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users".
 */
export interface PayloadUser {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-pages".
 */
export interface PayloadPage {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('main' | 'services' | 'solutions' | 'case-study' | 'demo') | null;
  parentPage?: (number | null) | PayloadPage;
  internalLinks?: (number | PayloadPage)[] | null;
  seo?: {
    metaDescription?: string | null;
    metaKeywords?: string | null;
    canonicalUrl?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | PayloadMedia;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (number | null) | PayloadMedia;
    noIndex?: boolean | null;
  };
  isHomepage?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-media".
 */
export interface PayloadMedia {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-blog-posts".
 */
export interface PayloadBlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | PayloadMedia;
  featuredImageAlt?: string | null;
  author: string;
  category?: ('ai-ml' | 'product-dev' | 'case-studies' | 'company-news') | null;
  seoKeywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  readingTime?: number | null;
  chapters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  internalLinks?:
    | (
        | {
            relationTo: 'payload-pages';
            value: number | PayloadPage;
          }
        | {
            relationTo: 'payload-blog-posts';
            value: number | PayloadBlogPost;
          }
      )[]
    | null;
  externalSources?:
    | {
        title?: string | null;
        url?: string | null;
        type?: ('article' | 'video' | 'documentation' | 'research') | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-services".
 */
export interface PayloadService {
  id: number;
  title: string;
  link: string;
  icon?: string | null;
  pageTitle?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description: string;
  tagline?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        title: string;
        images?:
          | {
              image?: (number | null) | PayloadMedia;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        tool?: string | null;
        id?: string | null;
      }[]
    | null;
  toolIcons?:
    | {
        iconName?: string | null;
        id?: string | null;
      }[]
    | null;
  hidden?: boolean | null;
  customCTA?: {
    text?: string | null;
    href?: string | null;
    secondary?: {
      text?: string | null;
      href?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'payload-users';
        value: number | PayloadUser;
      } | null)
    | ({
        relationTo: 'payload-pages';
        value: number | PayloadPage;
      } | null)
    | ({
        relationTo: 'payload-blog-posts';
        value: number | PayloadBlogPost;
      } | null)
    | ({
        relationTo: 'payload-media';
        value: number | PayloadMedia;
      } | null)
    | ({
        relationTo: 'payload-services';
        value: number | PayloadService;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'payload-users';
    value: number | PayloadUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'payload-users';
    value: number | PayloadUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users_select".
 */
export interface PayloadUsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-pages_select".
 */
export interface PayloadPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  category?: T;
  parentPage?: T;
  internalLinks?: T;
  seo?:
    | T
    | {
        metaDescription?: T;
        metaKeywords?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        noIndex?: T;
      };
  isHomepage?: T;
  meta?:
    | T
    | {
        overview?: T;
        title?: T;
        description?: T;
        preview?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-blog-posts_select".
 */
export interface PayloadBlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  author?: T;
  category?: T;
  seoKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  readingTime?: T;
  chapters?: T;
  internalLinks?: T;
  externalSources?:
    | T
    | {
        title?: T;
        url?: T;
        type?: T;
        id?: T;
      };
  publishedAt?: T;
  meta?:
    | T
    | {
        overview?: T;
        title?: T;
        description?: T;
        preview?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-media_select".
 */
export interface PayloadMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-services_select".
 */
export interface PayloadServicesSelect<T extends boolean = true> {
  title?: T;
  link?: T;
  icon?: T;
  pageTitle?: T;
  description?: T;
  tagline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  tools?:
    | T
    | {
        tool?: T;
        id?: T;
      };
  toolIcons?:
    | T
    | {
        iconName?: T;
        id?: T;
      };
  hidden?: T;
  customCTA?:
    | T
    | {
        text?: T;
        href?: T;
        secondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}